version: '3.3'
services:
  kcapp_odds_db:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    restart: always
    environment:
      MYSQL_DATABASE: 'kcapp-odds'
      MYSQL_USER: 'kcapp'
      MYSQL_PASSWORD: 'abcd1234'
      MYSQL_ROOT_PASSWORD: 'abcd1234'
    ports:
      - '3666:3306'
    expose:
      - '3666'
    volumes:
      - kcapp-odds-db:/var/lib/mysql
volumes:
  kcapp-odds-db:
